
rm(a3.constraint,
   b2.constraint,
   g.pot.start.index,
   calculate.covariance, 
   format.output,
   getFRED,
   gradient,
   kalman.log.likelihood,
   kalman.standard.errors,
   kalman.states,
   kalman.states.filtered,
   kalman.states.smoothed,
   kalman.states.wrapper,
   log.likelihood.wrapper,
   median.unbiased.estimator.stage1,
   median.unbiased.estimator.stage2,
   rstar.stage1,
   rstar.stage2,
   rstar.stage3,
   run.hlw.estimation,
   shiftMonth,
   shiftQuarter,
   splice,
   unpack.parameters.stage1,
   unpack.parameters.stage2,
   unpack.parameters.stage3)

